Add windows draw flow and communication
XavierCL/UnitWorld-solo pull request #2
Opened 2019-04-27 22:41 UTC by XavierCL

2019-04-27 22:56 UTC, XavierCL commented on Communications/communications/ConnectionInfo.h
> +		return _host;
Should be spaces

2019-04-27 22:59 UTC, XavierCL commented on Communications/communications/ConnectionInfo.h
> +	ConnectionInfo(const std::string& host, const std::string& port):
Should use cpp instead of only .h

2019-04-27 23:09 UTC, XavierCL commented on UnitWorld_client_gui/graphics/shared/SharedDisplay.h
> +		virtual void tryClose() = 0;
What's the link between the `SharedDisplay` class name and tryClose function? What,s this class?

2019-04-27 23:09 UTC, XavierCL commented on UnitWorld_client_gui/graphics/shared/SharedDrawer.h
> +	class SharedDrawer
Same here, why is this shared?

2019-04-27 23:16 UTC, XavierCL commented on UnitWorld_shared/game/physics/Vector2.h
> +#pragma once
Why does this class exist, use Vector2D

2019-04-28 16:05 UTC, ljleb requested changes

2019-04-28 16:05 UTC, ljleb commented on Commons/commons/FastMath.cpp
> +const unsigned char FastMath::debruijn64Table[64] = {
What's the purpose of this?

2019-04-28 16:05 UTC, ljleb commented on Communications/communications/ClientConnector.h
> +	ClientConnector(const ConnectionInfo& connectionInfo, const std::function<void(std::shared_ptr<CommunicationHandler>)>& serverConnectedCallback)
I suggest to add integration tests for this

2019-04-28 16:05 UTC, ljleb commented on Communications/communications/CommunicationHandler.h
> +
there should at least be a `// TOTO: ...` or a `throw NotImplemented` here to specify that this is not implemented

2019-04-28 16:05 UTC, ljleb commented on Communications/communications/CommunicationHandler.h
> +	{
not implemented

2019-04-28 16:05 UTC, ljleb commented on UnitWorld_client_gui/game/GameLoop.h
> +		static const bool GAME_STATE_RUNNING = false;
this should be refactored into an enum

2019-04-28 16:05 UTC, ljleb commented on UnitWorld_client_gui/game/GameLoop.h
> +		std::shared_ptr<SharedDrawer> _drawer;
should be `const`

2019-04-28 16:05 UTC, ljleb commented on UnitWorld_client_gui/game/GameLoop.h
> +#pragma once
implementation should be in `.cpp`

2019-04-28 16:05 UTC, ljleb commented on UnitWorld_client_gui/game/GameLoop.h
> +		}
command query is violated

2019-04-28 16:11 UTC, ljleb requested changes

2019-04-28 16:11 UTC, lebel-louisjacob commented on Communications/communications/CommunicationHandler.h
> +    {
`// TODO: ...` or `throw NotImplemented` here

2019-04-28 16:13 UTC, lebel-louisjacob commented on UnitWorld_client_gui/Main.cpp
> +    return EXIT_SUCCESS;
We will re-implement `main()` in a future PR

2019-04-28 16:57 UTC, XavierCL commented on Commons/commons/FastMath.cpp
> +const unsigned char FastMath::debruijn64Table[64] = {
Commons library, ask the author for changes if needed

2019-04-28 16:57 UTC, XavierCL commented on Communications/communications/ClientConnector.h
> +	ClientConnector(const ConnectionInfo& connectionInfo, const std::function<void(std::shared_ptr<CommunicationHandler>)>& serverConnectedCallback)
I suggest we do that later on, this is really an edge case network

2019-04-28 18:13 UTC, ljleb requested changes

2019-04-28 18:13 UTC, lebel-louisjacob commented on UnitWorld_shared/game/play/MobileUnit.h
> +        Vector2D* _destination;
should be `std::shared_ptr<Vector2D>`

2019-04-28 18:34 UTC, ljleb approved these changes

2019-04-28 18:37 UTC, merged